/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package student_registration_mgt;

import com.sun.istack.internal.logging.Logger;
import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.logging.Level;
import javax.swing.JOptionPane;
import sun.util.logging.PlatformLogger;

/**
 *
 * @author core i trading
 */
public class Contact extends javax.swing.JFrame {

    /**
     * Creates new form Contact
     */
    public Contact() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        abdi = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        tell = new javax.swing.JLabel();
        mail = new javax.swing.JLabel();
        face = new javax.swing.JLabel();
        twit = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 500));
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.pink, java.awt.Color.gray));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("This System is Developed by  ");

        abdi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/student_registration_mgt/hacker.jpg"))); // NOI18N
        abdi.setText("jLabel1");

        name.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        name.setIcon(new javax.swing.ImageIcon(getClass().getResource("/student_registration_mgt/user_32.png"))); // NOI18N
        name.setText("Guled Ali");
        name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nameMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nameMousePressed(evt);
            }
        });

        tell.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tell.setIcon(new javax.swing.ImageIcon(getClass().getResource("/student_registration_mgt/phone_32.png"))); // NOI18N
        tell.setText("+251911028177");

        mail.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        mail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/student_registration_mgt/gmail_32.png"))); // NOI18N
        mail.setText("guledali1431177@gmail.com");
        mail.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mailMousePressed(evt);
            }
        });

        face.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        face.setForeground(new java.awt.Color(0, 51, 51));
        face.setIcon(new javax.swing.ImageIcon(getClass().getResource("/student_registration_mgt/facebook_32.png"))); // NOI18N
        face.setText("Happy Hero Boy");
        face.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        face.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                faceMousePressed(evt);
            }
        });

        twit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        twit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/student_registration_mgt/twitter2_32.png"))); // NOI18N
        twit.setText("@guledal52044130");
        twit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        twit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                twitMousePressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/student_registration_mgt/youtube_32.png"))); // NOI18N
        jLabel3.setText("GuyoTube");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel3MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(abdi, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(351, 351, 351)
                                .addComponent(jLabel2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(twit)
                                        .addComponent(jLabel3)
                                        .addComponent(name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tell, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(mail)
                                    .addComponent(face, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(57, 57, 57)
                        .addComponent(name)
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tell)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addComponent(mail)
                        .addGap(18, 18, 18)
                        .addComponent(face))
                    .addComponent(abdi))
                .addGap(18, 18, 18)
                .addComponent(twit)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameMousePressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_nameMousePressed

    private void nameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_nameMouseExited

    private void faceMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_faceMousePressed
        // TODO add your handling code here:
           URI uri;
        try {
            uri = new URI("http://www.facebook.com/happyheroboy");
            open(uri);
        }
        catch (URISyntaxException ex) {
            java.util.logging.Logger.getLogger(Contact.class.getName()).log(Level.SEVERE, null, ex);
        }      
    }//GEN-LAST:event_faceMousePressed

    private void jLabel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MousePressed
        URI uri ;
        try {
            uri = new URI("http://www.youtube.com");
        } catch (URISyntaxException ex) {
            java.util.logging.Logger.getLogger(Contact.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel3MousePressed

    private void mailMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mailMousePressed
        // TODO add your handling code here:
        URI uri;
        try {
            uri = new URI("https://mail.google.com/mail/guledali1431177@gmail.com");
        } 
        catch (URISyntaxException ex) {
            java.util.logging.Logger.getLogger(Contact.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mailMousePressed

    private void twitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_twitMousePressed
        // TODO add your handling code here:
        URI uri;
        try {
            uri = new URI ("http://desktop.twitter.com/session/@guledal52044130");
        } catch (URISyntaxException ex) {
            java.util.logging.Logger.getLogger(Contact.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_twitMousePressed
   private static void open (URI uri){
    try{
        Desktop.getDesktop().browse(uri);
    }
    catch(IOException e){
        System.out.println(e);
    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Contact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Contact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Contact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Contact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Contact().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel abdi;
    private javax.swing.JLabel face;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel mail;
    private javax.swing.JLabel name;
    private javax.swing.JLabel tell;
    private javax.swing.JLabel twit;
    // End of variables declaration//GEN-END:variables

    
}
