package student_registration_mgt;

import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.sql.*;
import javax.swing.*;
public class Login extends javax.swing.JFrame {  
Connection con=null;
ResultSet set=null;
PreparedStatement pst=null;
 String g;
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
        Fpanel.setVisible(false);
        con=javaconnect.ConnectDB();
        g =uname.getText();
        ComboBox();
        uname.addFocusListener(new FocusListener(){
            
            public void focusGained(FocusEvent fe) {
                if(uname.getText().equalsIgnoreCase("USER NAME")){
                    uname.setText("");
                }
            }
            public void focusLost(FocusEvent fe) {
                if(uname.getText().equalsIgnoreCase("")){
                    uname.setText("USER NAME");
                }
            }
        });
            pass.addFocusListener(new FocusListener(){
            
            public void focusGained(FocusEvent fe) {
                if(pass.getText().equalsIgnoreCase("PASSWORD")){
                    pass.setText("");
                }
            }
            
            public void focusLost(FocusEvent fe) {
                if(pass.getText().equalsIgnoreCase("")){
                    pass.setText("PASSWORD");
                }
            }
            
        });
             Uname.addFocusListener(new FocusListener(){
            
            public void focusGained(FocusEvent fe) {
                if(Uname.getText().equalsIgnoreCase("USER NAME")){
                    Uname.setText("");
                }
            }
            
            public void focusLost(FocusEvent fe) {
                if(Uname.getText().equalsIgnoreCase("")){
                    Uname.setText("USER NAME");
                }
            }
        });
             role.addFocusListener(new FocusListener(){
            public void focusGained(FocusEvent fe) {
                if(role.getText().equalsIgnoreCase("Role")){
                    role.setText("");
                }
            }
            public void focusLost(FocusEvent fe) {
                if(role.getText().equalsIgnoreCase("")){
                    role.setText("Role");
                }
            }   
        });
              securty.addFocusListener(new FocusListener(){
            
            public void focusGained(FocusEvent fe) {
                if(securty.getText().equalsIgnoreCase("Security Question")){
                    securty.setText("");
                }
            }
            
            public void focusLost(FocusEvent fe) {
                if(securty.getText().equalsIgnoreCase("")){
                    securty.setText("Security Question");
                }
            }    
        });
             Ans.addFocusListener(new FocusListener(){
            
            public void focusGained(FocusEvent fe) {
                if(Ans.getText().equalsIgnoreCase("Answer")){
                    Ans.setText("");
                }
            }
            
            public void focusLost(FocusEvent fe) {
                if(Ans.getText().equalsIgnoreCase("")){
                    Ans.setText("Answer");
                }
            }    
        });
            Pass.addFocusListener(new FocusListener(){
            
            public void focusGained(FocusEvent fe) {
                    if(Pass.getText().equalsIgnoreCase("YOUR Answer IS ...")){
                    Pass.setText("");
                }
            }
            
            public void focusLost(FocusEvent fe) {
                if(Pass.getText().equalsIgnoreCase("")){
                    Pass.setText("YOUR Answer IS ...");
                }
            }    
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Lpanel = new javax.swing.JPanel();
        cb = new javax.swing.JComboBox<>();
        uname = new javax.swing.JTextField();
        pass = new javax.swing.JPasswordField();
        forgetpassword = new javax.swing.JLabel();
        Login = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        Fpanel = new javax.swing.JPanel();
        Uname = new javax.swing.JTextField();
        role = new javax.swing.JTextField();
        securty = new javax.swing.JTextField();
        Ans = new javax.swing.JTextField();
        Pass = new javax.swing.JTextField();
        Search = new javax.swing.JButton();
        Retrieve = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        Lpanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 51, 255), new java.awt.Color(51, 102, 255), new java.awt.Color(0, 0, 255), new java.awt.Color(0, 51, 255)));

        cb.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        uname.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        uname.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        pass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pass.setToolTipText("PASSWORD");

        forgetpassword.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        forgetpassword.setText("Forget Password");
        forgetpassword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        forgetpassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                forgetpasswordMousePressed(evt);
            }
        });

        Login.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/student_registration_mgt/log_32.png"))); // NOI18N
        Login.setText("in");
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });
        Login.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                LoginKeyPressed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/student_registration_mgt/show_password_32.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LpanelLayout = new javax.swing.GroupLayout(Lpanel);
        Lpanel.setLayout(LpanelLayout);
        LpanelLayout.setHorizontalGroup(
            LpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LpanelLayout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addGroup(LpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(uname, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(LpanelLayout.createSequentialGroup()
                        .addGroup(LpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Login)
                            .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43))
            .addGroup(LpanelLayout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(forgetpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        LpanelLayout.setVerticalGroup(
            LpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LpanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(uname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(LpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(Login, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(forgetpassword)
                .addGap(19, 19, 19))
        );

        Fpanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 255, 255), new java.awt.Color(51, 255, 255), new java.awt.Color(51, 255, 255), new java.awt.Color(102, 255, 255)));

        Uname.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Uname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Uname.setText("USER NAME");

        role.setEditable(false);
        role.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        role.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        role.setText("Role");

        securty.setEditable(false);
        securty.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        securty.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        securty.setText("Security Question");

        Ans.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Ans.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Ans.setText("Answer");

        Pass.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Pass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Pass.setText("YOUR Answer IS ...");

        Search.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/student_registration_mgt/search_32.png"))); // NOI18N
        Search.setText("Search");
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });

        Retrieve.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Retrieve.setIcon(new javax.swing.ImageIcon(getClass().getResource("/student_registration_mgt/get_32.png"))); // NOI18N
        Retrieve.setText("Retrive");
        Retrieve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetrieveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FpanelLayout = new javax.swing.GroupLayout(Fpanel);
        Fpanel.setLayout(FpanelLayout);
        FpanelLayout.setHorizontalGroup(
            FpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FpanelLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(FpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Ans)
                    .addComponent(role)
                    .addComponent(Uname)
                    .addComponent(securty)
                    .addComponent(Pass))
                .addContainerGap(194, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FpanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(FpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Retrieve)
                    .addComponent(Search))
                .addGap(39, 39, 39))
        );
        FpanelLayout.setVerticalGroup(
            FpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FpanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(Search, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Uname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(role, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(securty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(Ans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Retrieve, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Lpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Fpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Lpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Fpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void forgetpasswordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgetpasswordMousePressed
        // TODO add your handling code here:
        Fpanel.setVisible(true);
    }//GEN-LAST:event_forgetpasswordMousePressed

    private void RetrieveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetrieveActionPerformed
        // TODO add your handling code here:
        retrieve();
    }//GEN-LAST:event_RetrieveActionPerformed

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
        // TODO add your handling code here:
      String choise = (String) cb.getSelectedItem();
      String UName = uname.getText();
      String Pswd =  pass.getText();
      try{
        if(UName.equalsIgnoreCase("") && Pswd.equalsIgnoreCase("") && !choise.equalsIgnoreCase("")){
          JOptionPane.showMessageDialog(null, "Enter User Name & Password", "Access Denied",JOptionPane.ERROR_MESSAGE);
               }
        else{
          String sql="SELECT * FROM USER WHERE User_Name = ? and Password = ? and Post = ?";
          pst  = con.prepareStatement(sql);
          pst.setString(1, UName);
          pst.setString(2, Pswd);
          pst.setString(3, choise);
          set=pst.executeQuery();
          if(set.next()){
              
              String name = set.getString("User_Name");
              String Password = set.getString("Password");
              String role = set.getString("Post");

                  if(choise.equals("Admin")||choise.equals("Staff")&&UName.equals(name)&&Pswd.equals(Password)){
                  String possition = null;
                  Home_Page m = new Home_Page(possition);
                  m.setVisible(true);
                  m.reg.setEnabled(true);
                  setVisible(true);
                  dispose();
              }
                 else if(choise.equals(role)&&UName.equals(name)&&Pswd.equals(Password)){
                  String possition = null;
                  Std_Home_Page m = new Std_Home_Page();
                  m.setVisible(true);
                 // m.reg.setEnabled(false);
                  setVisible(true);
                  dispose();
              }
          }
          else{
          JOptionPane.showMessageDialog(null, "Wrong Username and Password");
      }
        }
      }
      catch(Exception e){
          JOptionPane.showMessageDialog(this, e);
      }
    }//GEN-LAST:event_LoginActionPerformed

    private void LoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LoginKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginKeyPressed

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        // TODO add your handling code here:
         search();
    }//GEN-LAST:event_SearchActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        pass.setEchoChar((char)0);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    private void ComboBox(){
        try{
            String sql="SELECT * FROM USER";
            pst = con.prepareStatement(sql);
            set = pst.executeQuery();
            while(set.next()){
                String rol = set.getString("Post");
                cb.addItem(rol);
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
    }
    public void retrieve(){
        String a =Uname.getText();
        String b= Ans.getText();
        try{
            String sql ="SELECT * FROM `USER` WHERE User_Name ='"+a+"' and Answer ='"+b+"'";
            pst=con.prepareStatement(sql);
            set=pst.executeQuery();
            if(set.next()){
                Pass.setText(set.getString(3));
                set.close();
                pst.close();
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
     public void search(){
        try{
            String a1 = Uname.getText();
            String sql ="SELECT * FROM `USER` WHERE `User_Name`='"+a1+"'";
            pst = con.prepareStatement(sql);
            set = pst.executeQuery();
            if(set.next()){
            role.setText(set.getString(4));
            securty.setText(set.getString(5));
            set.close();
            pst.close();
          }
           else{
               
            JOptionPane.showMessageDialog(null, "Incorect user name");
            
        }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Ans;
    private javax.swing.JPanel Fpanel;
    private javax.swing.JButton Login;
    private javax.swing.JPanel Lpanel;
    private javax.swing.JTextField Pass;
    private javax.swing.JButton Retrieve;
    private javax.swing.JButton Search;
    private javax.swing.JTextField Uname;
    private javax.swing.JComboBox<String> cb;
    private javax.swing.JLabel forgetpassword;
    private javax.swing.JButton jButton1;
    private javax.swing.JPasswordField pass;
    private javax.swing.JTextField role;
    private javax.swing.JTextField securty;
    public static javax.swing.JTextField uname;
    // End of variables declaration//GEN-END:variables
}
